/* The following code was generated by JFlex 1.7.0 */

package Scanner;


import Parser.Tokens;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>C:/pascal.jflex</tt>
 */
public class PascalLex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\16\1\2\1\3\1\2\1\2\22\0\1\16\1\0\1\12"+
    "\2\0\1\66\1\64\1\13\1\55\1\57\1\62\1\61\1\53\1\1"+
    "\1\46\1\4\1\7\11\45\1\51\1\60\1\5\1\52\1\6\2\0"+
    "\6\11\21\47\1\10\2\47\1\54\1\0\1\56\1\63\1\50\1\0"+
    "\1\17\1\25\1\31\1\24\1\27\1\36\1\22\1\41\1\21\1\47"+
    "\1\30\1\37\1\43\1\23\1\32\1\42\1\47\1\26\1\20\1\33"+
    "\1\34\1\44\1\40\1\10\1\35\1\47\1\15\1\65\1\14\1\67"+
    "\6\0\1\3\u1fa2\0\1\3\1\3\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\2\1\1\11\1\12\17\10\1\3\1\7\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\3"+
    "\1\33\1\34\1\3\1\0\1\35\1\36\1\37\3\0"+
    "\1\40\1\0\5\10\1\41\1\10\1\42\10\10\1\43"+
    "\1\44\10\10\1\3\1\45\1\0\2\46\1\47\1\50"+
    "\1\10\1\51\3\10\1\52\5\10\1\53\12\10\1\54"+
    "\1\0\7\10\1\55\1\10\1\56\1\10\1\57\1\60"+
    "\1\61\1\10\1\62\3\10\1\0\1\10\1\63\2\10"+
    "\1\64\1\65\4\10\1\66\2\10\1\45\1\67\2\10"+
    "\1\70\4\10\1\71\1\72\2\10\1\73\1\10\1\74"+
    "\1\75\1\10\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[169];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\u0188"+
    "\0\u01c0\0\u01f8\0\u0230\0\u0268\0\160\0\160\0\u02a0\0\u02d8"+
    "\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498"+
    "\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620\0\160"+
    "\0\u0658\0\160\0\160\0\160\0\160\0\160\0\160\0\160"+
    "\0\160\0\160\0\160\0\160\0\160\0\160\0\160\0\160"+
    "\0\160\0\160\0\u0690\0\u06c8\0\160\0\160\0\160\0\u0700"+
    "\0\u0738\0\u0230\0\160\0\u0770\0\u07a8\0\u07e0\0\u0818\0\u0850"+
    "\0\u0888\0\u01f8\0\u08c0\0\u01f8\0\u08f8\0\u0930\0\u0968\0\u09a0"+
    "\0\u09d8\0\u0a10\0\u0a48\0\u0a80\0\u01f8\0\u01f8\0\u0ab8\0\u0af0"+
    "\0\u0b28\0\u0b60\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0c78\0\160"+
    "\0\u0cb0\0\160\0\u0ce8\0\u0738\0\160\0\u0d20\0\u01f8\0\u0d58"+
    "\0\u0d90\0\u0dc8\0\u01f8\0\u0e00\0\u0e38\0\u0e70\0\u0ea8\0\u0ee0"+
    "\0\u01f8\0\u0f18\0\u0f50\0\u0f88\0\u0fc0\0\u0ff8\0\u1030\0\u1068"+
    "\0\u10a0\0\u10d8\0\u1110\0\u01f8\0\u1148\0\u1180\0\u11b8\0\u11f0"+
    "\0\u1228\0\u1260\0\u1298\0\u12d0\0\u01f8\0\u1308\0\u01f8\0\u1340"+
    "\0\u01f8\0\u01f8\0\u01f8\0\u1378\0\u01f8\0\u13b0\0\u13e8\0\u1420"+
    "\0\u1458\0\u1490\0\u01f8\0\u14c8\0\u1500\0\u01f8\0\u01f8\0\u1538"+
    "\0\u1570\0\u15a8\0\u15e0\0\u01f8\0\u1618\0\u1650\0\u01f8\0\u01f8"+
    "\0\u1688\0\u16c0\0\u01f8\0\u16f8\0\u1730\0\u1768\0\u17a0\0\u01f8"+
    "\0\u01f8\0\u17d8\0\u1810\0\u01f8\0\u1848\0\u01f8\0\u01f8\0\u1880"+
    "\0\u01f8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[169];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\0\1\6\1\7\1\10\1\11"+
    "\2\12\1\13\1\14\1\15\1\16\1\5\1\17\1\20"+
    "\1\21\1\12\1\22\1\23\1\24\1\25\1\26\1\12"+
    "\1\27\1\30\1\31\2\12\1\32\1\33\1\34\1\12"+
    "\1\35\1\12\1\36\1\37\1\40\1\12\1\3\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\2\60\1\5"+
    "\1\0\10\60\1\61\1\62\1\5\25\60\1\5\23\60"+
    "\71\0\1\63\70\0\1\5\13\0\1\5\25\0\1\5"+
    "\27\0\1\63\64\0\1\64\4\0\1\65\43\0\1\66"+
    "\67\0\1\67\25\0\1\70\35\0\1\71\30\0\3\12"+
    "\5\0\27\12\1\0\2\12\17\0\12\72\1\73\55\72"+
    "\13\74\1\0\54\74\7\0\3\12\5\0\1\12\1\75"+
    "\2\12\1\76\2\12\1\77\17\12\1\0\2\12\26\0"+
    "\3\12\5\0\14\12\1\100\12\12\1\0\2\12\26\0"+
    "\3\12\5\0\4\12\1\101\12\12\1\102\7\12\1\0"+
    "\2\12\26\0\3\12\5\0\13\12\1\103\13\12\1\0"+
    "\2\12\26\0\3\12\5\0\13\12\1\104\13\12\1\0"+
    "\2\12\26\0\3\12\5\0\7\12\1\105\1\106\2\12"+
    "\1\107\13\12\1\0\2\12\26\0\3\12\5\0\10\12"+
    "\1\110\16\12\1\0\2\12\26\0\3\12\5\0\4\12"+
    "\1\111\13\12\1\112\6\12\1\0\2\12\26\0\3\12"+
    "\5\0\13\12\1\113\6\12\1\114\4\12\1\0\2\12"+
    "\26\0\3\12\5\0\7\12\1\115\7\12\1\116\7\12"+
    "\1\0\2\12\26\0\3\12\5\0\7\12\1\117\12\12"+
    "\1\120\4\12\1\0\2\12\26\0\3\12\5\0\1\121"+
    "\14\12\1\122\11\12\1\0\2\12\26\0\3\12\5\0"+
    "\13\12\1\123\13\12\1\0\2\12\26\0\3\12\5\0"+
    "\22\12\1\124\4\12\1\0\2\12\26\0\3\12\5\0"+
    "\7\12\1\125\17\12\1\0\2\12\21\0\1\5\4\0"+
    "\3\12\4\0\1\5\1\126\24\12\1\127\1\12\1\0"+
    "\2\12\26\0\1\37\35\0\1\37\1\71\73\0\1\130"+
    "\15\0\2\63\2\0\64\63\1\0\1\131\75\0\1\132"+
    "\1\0\1\133\33\0\1\133\31\0\1\134\35\0\1\134"+
    "\35\0\1\135\63\0\3\12\5\0\1\12\1\136\25\12"+
    "\1\0\2\12\26\0\3\12\5\0\5\12\1\137\21\12"+
    "\1\0\2\12\26\0\3\12\5\0\7\12\1\140\17\12"+
    "\1\0\2\12\26\0\3\12\5\0\7\12\1\141\17\12"+
    "\1\0\2\12\26\0\3\12\5\0\14\12\1\142\12\12"+
    "\1\0\2\12\26\0\3\12\5\0\14\12\1\143\12\12"+
    "\1\0\2\12\26\0\3\12\5\0\10\12\1\144\16\12"+
    "\1\0\2\12\26\0\3\12\5\0\3\12\1\145\23\12"+
    "\1\0\2\12\26\0\3\12\5\0\13\12\1\146\13\12"+
    "\1\0\2\12\26\0\3\12\5\0\1\147\13\12\1\150"+
    "\12\12\1\0\2\12\26\0\3\12\5\0\5\12\1\151"+
    "\21\12\1\0\2\12\26\0\3\12\5\0\1\12\1\152"+
    "\25\12\1\0\2\12\26\0\3\12\5\0\4\12\1\153"+
    "\22\12\1\0\2\12\26\0\3\12\5\0\1\154\26\12"+
    "\1\0\2\12\26\0\3\12\5\0\15\12\1\155\11\12"+
    "\1\0\2\12\26\0\3\12\5\0\10\12\1\156\16\12"+
    "\1\0\2\12\26\0\3\12\5\0\20\12\1\157\6\12"+
    "\1\0\2\12\26\0\3\12\5\0\4\12\1\160\22\12"+
    "\1\0\2\12\26\0\3\12\5\0\4\12\1\161\22\12"+
    "\1\0\2\12\26\0\3\12\5\0\2\12\1\162\24\12"+
    "\1\0\2\12\26\0\3\12\5\0\13\12\1\163\13\12"+
    "\1\0\2\12\26\0\3\12\5\0\7\12\1\164\17\12"+
    "\1\0\2\12\21\0\1\5\4\0\3\12\4\0\1\5"+
    "\25\12\1\127\1\12\1\0\2\12\17\0\1\131\1\165"+
    "\66\131\7\0\1\133\1\0\1\133\33\0\1\133\31\0"+
    "\3\12\5\0\2\12\1\166\24\12\1\0\2\12\26\0"+
    "\3\12\5\0\1\167\26\12\1\0\2\12\26\0\3\12"+
    "\5\0\2\12\1\170\24\12\1\0\2\12\26\0\3\12"+
    "\5\0\10\12\1\171\16\12\1\0\2\12\26\0\3\12"+
    "\5\0\1\172\26\12\1\0\2\12\26\0\3\12\5\0"+
    "\2\12\1\173\24\12\1\0\2\12\26\0\3\12\5\0"+
    "\20\12\1\174\6\12\1\0\2\12\26\0\3\12\5\0"+
    "\20\12\1\175\6\12\1\0\2\12\26\0\3\12\5\0"+
    "\15\12\1\176\11\12\1\0\2\12\26\0\3\12\5\0"+
    "\10\12\1\177\16\12\1\0\2\12\26\0\3\12\5\0"+
    "\14\12\1\200\12\12\1\0\2\12\26\0\3\12\5\0"+
    "\7\12\1\201\17\12\1\0\2\12\26\0\3\12\5\0"+
    "\10\12\1\202\16\12\1\0\2\12\26\0\3\12\5\0"+
    "\4\12\1\203\22\12\1\0\2\12\26\0\3\12\5\0"+
    "\1\12\1\155\25\12\1\0\2\12\26\0\3\12\5\0"+
    "\12\12\1\204\14\12\1\0\2\12\26\0\3\12\5\0"+
    "\3\12\1\205\23\12\1\0\2\12\26\0\3\12\5\0"+
    "\20\12\1\206\6\12\1\0\2\12\26\0\3\12\5\0"+
    "\3\12\1\207\6\12\1\210\14\12\1\0\2\12\17\0"+
    "\1\131\1\211\66\131\7\0\3\12\5\0\3\12\1\212"+
    "\23\12\1\0\2\12\26\0\3\12\5\0\16\12\1\213"+
    "\10\12\1\0\2\12\26\0\3\12\5\0\4\12\1\214"+
    "\22\12\1\0\2\12\26\0\3\12\5\0\3\12\1\215"+
    "\23\12\1\0\2\12\26\0\3\12\5\0\11\12\1\216"+
    "\15\12\1\0\2\12\26\0\3\12\5\0\4\12\1\217"+
    "\22\12\1\0\2\12\26\0\3\12\5\0\10\12\1\220"+
    "\16\12\1\0\2\12\26\0\3\12\5\0\7\12\1\221"+
    "\17\12\1\0\2\12\26\0\3\12\5\0\2\12\1\222"+
    "\24\12\1\0\2\12\26\0\3\12\5\0\14\12\1\223"+
    "\12\12\1\0\2\12\26\0\3\12\5\0\10\12\1\224"+
    "\16\12\1\0\2\12\26\0\3\12\5\0\7\12\1\225"+
    "\17\12\1\0\2\12\26\0\3\12\5\0\10\12\1\226"+
    "\16\12\1\0\2\12\17\0\6\131\1\60\61\131\7\0"+
    "\3\12\5\0\4\12\1\227\22\12\1\0\2\12\26\0"+
    "\3\12\5\0\3\12\1\230\23\12\1\0\2\12\26\0"+
    "\3\12\5\0\10\12\1\231\16\12\1\0\2\12\26\0"+
    "\3\12\5\0\1\232\26\12\1\0\2\12\26\0\3\12"+
    "\5\0\4\12\1\233\22\12\1\0\2\12\26\0\3\12"+
    "\5\0\4\12\1\234\22\12\1\0\2\12\26\0\3\12"+
    "\5\0\2\12\1\235\24\12\1\0\2\12\26\0\3\12"+
    "\5\0\1\236\26\12\1\0\2\12\26\0\3\12\5\0"+
    "\5\12\1\237\21\12\1\0\2\12\26\0\3\12\5\0"+
    "\7\12\1\240\17\12\1\0\2\12\26\0\3\12\5\0"+
    "\4\12\1\241\22\12\1\0\2\12\26\0\3\12\5\0"+
    "\15\12\1\242\11\12\1\0\2\12\26\0\3\12\5\0"+
    "\13\12\1\243\13\12\1\0\2\12\26\0\3\12\5\0"+
    "\24\12\1\244\2\12\1\0\2\12\26\0\3\12\5\0"+
    "\15\12\1\245\11\12\1\0\2\12\26\0\3\12\5\0"+
    "\10\12\1\246\16\12\1\0\2\12\26\0\3\12\5\0"+
    "\4\12\1\247\22\12\1\0\2\12\26\0\3\12\5\0"+
    "\7\12\1\250\17\12\1\0\2\12\26\0\3\12\5\0"+
    "\10\12\1\251\16\12\1\0\2\12\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6328];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\11\1\2\11\21\1\1\11\1\1\21\11"+
    "\1\1\1\0\3\11\3\0\1\11\1\0\33\1\1\11"+
    "\1\0\1\11\2\1\1\11\27\1\1\0\23\1\1\0"+
    "\40\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[169];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol Symbol(int type) {
    	String sequence = yytext();
    	/*if(type == Tokens.CHAR_CONST) {
    		sequence = sequence.substring(1, sequence.length()-1);
    	}*/
    
    	if(sequence.equals("''''")) {
    		return new Symbol(type, yyline + 1, yycolumn + 1, "'");
    	}
        return new Symbol(type, yyline + 1, yycolumn + 1, sequence);
    }
int bracketCount = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PascalLex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 184) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	if(bracketCount == 0)
    	return new Symbol(Tokens.EOF);
    else {
    	Report.error("You forgot to close some of your { brackets! Compiler error at line "+yyline+", column "+yycolumn+".", yyline, yycolumn, -1);
    }
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { Report.error("Character not recognizable as valid Pascal keyword, symbol, name, ID or constant.", yyline+1, yycolumn+1, -1);
            } 
            // fall through
          case 63: break;
          case 2: 
            { return Symbol(Tokens.SUB);
            } 
            // fall through
          case 64: break;
          case 3: 
            { 
            } 
            // fall through
          case 65: break;
          case 4: 
            { return Symbol(Tokens.DIV);
            } 
            // fall through
          case 66: break;
          case 5: 
            { return Symbol(Tokens.LTH);
            } 
            // fall through
          case 67: break;
          case 6: 
            { return Symbol(Tokens.GTH);
            } 
            // fall through
          case 68: break;
          case 7: 
            { return Symbol(Tokens.INT_CONST);
            } 
            // fall through
          case 69: break;
          case 8: 
            { return Symbol(Tokens.ID);
            } 
            // fall through
          case 70: break;
          case 9: 
            { Report.error("At least one too many } in your code!", yyline+1, yycolumn+1, -1);
            } 
            // fall through
          case 71: break;
          case 10: 
            { bracketCount++; yybegin(COMMENT);
            } 
            // fall through
          case 72: break;
          case 11: 
            { return Symbol(Tokens.DOT);
            } 
            // fall through
          case 73: break;
          case 12: 
            { return Symbol(Tokens.COLON);
            } 
            // fall through
          case 74: break;
          case 13: 
            { return Symbol(Tokens.EQU);
            } 
            // fall through
          case 75: break;
          case 14: 
            { return Symbol(Tokens.COMMA);
            } 
            // fall through
          case 76: break;
          case 15: 
            { return Symbol(Tokens.LBR);
            } 
            // fall through
          case 77: break;
          case 16: 
            { return Symbol(Tokens.LPR);
            } 
            // fall through
          case 78: break;
          case 17: 
            { return Symbol(Tokens.RBR);
            } 
            // fall through
          case 79: break;
          case 18: 
            { return Symbol(Tokens.RPR);
            } 
            // fall through
          case 80: break;
          case 19: 
            { return Symbol(Tokens.SEMI);
            } 
            // fall through
          case 81: break;
          case 20: 
            { return Symbol(Tokens.ADD);
            } 
            // fall through
          case 82: break;
          case 21: 
            { return Symbol(Tokens.MUL);
            } 
            // fall through
          case 83: break;
          case 22: 
            { return Symbol(Tokens.XOR);
            } 
            // fall through
          case 84: break;
          case 23: 
            { return Symbol(Tokens.BAND);
            } 
            // fall through
          case 85: break;
          case 24: 
            { return Symbol(Tokens.BOR);
            } 
            // fall through
          case 86: break;
          case 25: 
            { return Symbol(Tokens.MOD);
            } 
            // fall through
          case 87: break;
          case 26: 
            { return Symbol(Tokens.LNOT);
            } 
            // fall through
          case 88: break;
          case 27: 
            { bracketCount --; 
									  if(bracketCount == 0) 
										yybegin(YYINITIAL);
            } 
            // fall through
          case 89: break;
          case 28: 
            { bracketCount++;
            } 
            // fall through
          case 90: break;
          case 29: 
            { return Symbol(Tokens.NEQ);
            } 
            // fall through
          case 91: break;
          case 30: 
            { return Symbol(Tokens.LEQ);
            } 
            // fall through
          case 92: break;
          case 31: 
            { return Symbol(Tokens.GEQ);
            } 
            // fall through
          case 93: break;
          case 32: 
            { return new Symbol(Tokens.STRING_CONST, yytext());
            } 
            // fall through
          case 94: break;
          case 33: 
            { return Symbol(Tokens.IF);
            } 
            // fall through
          case 95: break;
          case 34: 
            { return Symbol(Tokens.DO);
            } 
            // fall through
          case 96: break;
          case 35: 
            { return Symbol(Tokens.LOR);
            } 
            // fall through
          case 97: break;
          case 36: 
            { return Symbol(Tokens.OF);
            } 
            // fall through
          case 98: break;
          case 37: 
            { return Symbol(Tokens.ASSIGN);
            } 
            // fall through
          case 99: break;
          case 38: 
            { return Symbol(Tokens.HEX_CONST);
            } 
            // fall through
          case 100: break;
          case 39: 
            { return Symbol(Tokens.REAL_CONST);
            } 
            // fall through
          case 101: break;
          case 40: 
            { return new Symbol(Tokens.CHAR_CONST, yytext());
            } 
            // fall through
          case 102: break;
          case 41: 
            { return Symbol(Tokens.LAND);
            } 
            // fall through
          case 103: break;
          case 42: 
            { return Symbol(Tokens.NOT);
            } 
            // fall through
          case 104: break;
          case 43: 
            { return Symbol(Tokens.END);
            } 
            // fall through
          case 105: break;
          case 44: 
            { return Symbol(Tokens.VAR);
            } 
            // fall through
          case 106: break;
          case 45: 
            { return Symbol(Tokens.REAL);
            } 
            // fall through
          case 107: break;
          case 46: 
            { return Symbol(Tokens.ELSE);
            } 
            // fall through
          case 108: break;
          case 47: 
            { return Symbol(Tokens.CHAR);
            } 
            // fall through
          case 109: break;
          case 48: 
            { return Symbol(Tokens.BOOL_CONST);
            } 
            // fall through
          case 110: break;
          case 49: 
            { return Symbol(Tokens.THEN);
            } 
            // fall through
          case 111: break;
          case 50: 
            { return new Symbol(Tokens.LONG, yytext());
            } 
            // fall through
          case 112: break;
          case 51: 
            { return Symbol(Tokens.ARRAY);
            } 
            // fall through
          case 113: break;
          case 52: 
            { return Symbol(Tokens.BREAK);
            } 
            // fall through
          case 114: break;
          case 53: 
            { return Symbol(Tokens.BEGIN);
            } 
            // fall through
          case 115: break;
          case 54: 
            { return Symbol(Tokens.WHILE);
            } 
            // fall through
          case 116: break;
          case 55: 
            { return Symbol(Tokens.STRING);
            } 
            // fall through
          case 117: break;
          case 56: 
            { return Symbol(Tokens.RETURN);
            } 
            // fall through
          case 118: break;
          case 57: 
            { return Symbol(Tokens.INT);
            } 
            // fall through
          case 119: break;
          case 58: 
            { return Symbol(Tokens.BOOL);
            } 
            // fall through
          case 120: break;
          case 59: 
            { return Symbol(Tokens.PROGRAM);
            } 
            // fall through
          case 121: break;
          case 60: 
            { return Symbol(Tokens.CONTINUE);
            } 
            // fall through
          case 122: break;
          case 61: 
            { return Symbol(Tokens.FUNCTION);
            } 
            // fall through
          case 123: break;
          case 62: 
            { return Symbol(Tokens.PROCEDURE);
            } 
            // fall through
          case 124: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
