/* The following code was generated by JFlex 1.6.1 */

/*-***
 *
 * This file defines a stand-alone lexical analyzer for a subset of the Pascal
 * programming language.  This is the same lexer that will later be integrated
 * with a CUP-based parser.  Here the lexer is driven by the simple Java test
 * program in ./PascalLexerTest.java, q.v.  See 330 Lecture Notes 2 and the
 * Assignment 2 writeup for further discussion.
 *
 */

import java_cup.runtime.*;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>ppp.jflex</tt>
 */
class PascalLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\13\1\6\1\7\1\6\1\6\22\0\1\13\4\0\1\50"+
    "\1\45\1\5\1\54\1\55\1\42\1\43\1\53\1\10\1\4\1\44"+
    "\12\2\1\61\1\52\1\11\1\60\1\12\2\0\32\1\1\56\1\0"+
    "\1\57\1\51\1\3\1\0\1\22\1\15\1\34\1\23\1\16\1\37"+
    "\1\17\1\31\1\20\1\1\1\33\1\26\1\41\1\21\1\32\1\40"+
    "\1\1\1\24\1\27\1\35\1\36\1\14\1\30\1\1\1\25\1\1"+
    "\1\0\1\46\1\0\1\47\6\0\1\7\u1fa2\0\1\7\1\7\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\1\1\4\1\2\1\5\1\6"+
    "\1\7\1\10\16\3\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\2\0\1\32\1\33\1\34"+
    "\7\3\1\35\3\3\1\36\3\3\1\37\1\40\7\3"+
    "\1\41\1\42\1\0\1\43\3\3\1\44\2\3\1\45"+
    "\15\3\1\0\3\3\1\46\3\3\1\47\3\3\1\50"+
    "\1\3\1\51\1\52\4\3\1\0\1\53\1\54\2\3"+
    "\1\55\3\3\1\56\1\3\1\57\3\3\1\60\2\3"+
    "\1\61\1\62\1\63\4\3\1\64\1\65\2\3\1\66"+
    "\1\3\1\67\1\70\1\3\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\62\0\62"+
    "\0\u012c\0\u015e\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258\0\u028a"+
    "\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8\0\u041a"+
    "\0\62\0\62\0\62\0\62\0\62\0\62\0\62\0\62"+
    "\0\62\0\62\0\62\0\62\0\62\0\62\0\62\0\u044c"+
    "\0\310\0\u047e\0\u04b0\0\62\0\62\0\62\0\u04e2\0\u0514"+
    "\0\u0546\0\u0578\0\u05aa\0\u05dc\0\u060e\0\144\0\u0640\0\u0672"+
    "\0\u06a4\0\144\0\u06d6\0\u0708\0\u073a\0\144\0\144\0\u076c"+
    "\0\u079e\0\u07d0\0\u0802\0\u0834\0\u0866\0\u0898\0\62\0\62"+
    "\0\u08ca\0\144\0\u08fc\0\u092e\0\u0960\0\144\0\u0992\0\u09c4"+
    "\0\144\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0\0\u0b22"+
    "\0\u0b54\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\u0c80\0\u0cb2"+
    "\0\u0ce4\0\u0d16\0\144\0\u0d48\0\u0d7a\0\u0dac\0\144\0\u0dde"+
    "\0\u0e10\0\u0e42\0\144\0\u0e74\0\144\0\144\0\u0ea6\0\u0ed8"+
    "\0\u0f0a\0\u0f3c\0\u0f6e\0\144\0\144\0\u0fa0\0\u0fd2\0\144"+
    "\0\u1004\0\u1036\0\u1068\0\144\0\u109a\0\144\0\u10cc\0\u10fe"+
    "\0\u1130\0\62\0\u1162\0\u1194\0\144\0\144\0\144\0\u11c6"+
    "\0\u11f8\0\u122a\0\u125c\0\144\0\144\0\u128e\0\u12c0\0\144"+
    "\0\u12f2\0\144\0\144\0\u1324\0\144";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\7\1\0"+
    "\1\10\1\11\1\12\1\7\1\13\1\14\1\15\1\3"+
    "\1\16\1\3\1\17\1\20\1\21\2\3\1\22\1\23"+
    "\1\3\1\24\1\3\1\25\1\26\1\3\1\27\1\30"+
    "\1\3\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\63\0\3\3\10\0\26\3\22\0\1\4\1\0"+
    "\1\51\57\0\1\51\57\0\6\52\2\0\52\52\10\0"+
    "\1\53\1\0\1\54\45\0\1\55\61\0\1\56\2\0"+
    "\3\3\10\0\6\3\1\57\17\3\21\0\3\3\10\0"+
    "\2\3\1\60\5\3\1\61\5\3\1\62\7\3\21\0"+
    "\3\3\10\0\5\3\1\63\4\3\1\64\13\3\21\0"+
    "\3\3\10\0\5\3\1\65\15\3\1\66\2\3\21\0"+
    "\3\3\10\0\5\3\1\67\2\3\1\70\2\3\1\71"+
    "\12\3\21\0\3\3\10\0\16\3\1\72\7\3\21\0"+
    "\3\3\10\0\2\3\1\73\23\3\21\0\3\3\10\0"+
    "\21\3\1\74\4\3\21\0\3\3\10\0\15\3\1\75"+
    "\10\3\21\0\3\3\10\0\10\3\1\76\12\3\1\77"+
    "\2\3\21\0\3\3\10\0\15\3\1\100\1\101\7\3"+
    "\21\0\3\3\10\0\10\3\1\102\4\3\1\103\10\3"+
    "\21\0\3\3\10\0\6\3\1\104\13\3\1\105\3\3"+
    "\21\0\3\3\10\0\10\3\1\106\15\3\100\0\1\107"+
    "\6\0\1\110\64\0\1\111\52\0\3\3\10\0\10\3"+
    "\1\112\15\3\21\0\3\3\10\0\3\3\1\113\22\3"+
    "\21\0\3\3\10\0\2\3\1\114\23\3\21\0\3\3"+
    "\10\0\16\3\1\115\7\3\21\0\3\3\10\0\7\3"+
    "\1\116\16\3\21\0\3\3\10\0\13\3\1\117\12\3"+
    "\21\0\3\3\10\0\21\3\1\120\4\3\21\0\3\3"+
    "\10\0\7\3\1\121\16\3\21\0\3\3\10\0\10\3"+
    "\1\122\15\3\21\0\3\3\10\0\13\3\1\123\12\3"+
    "\21\0\3\3\10\0\6\3\1\124\12\3\1\125\4\3"+
    "\21\0\3\3\10\0\10\3\1\126\15\3\21\0\3\3"+
    "\10\0\4\3\1\127\21\3\21\0\3\3\10\0\6\3"+
    "\1\130\17\3\21\0\3\3\10\0\5\3\1\131\20\3"+
    "\21\0\3\3\10\0\22\3\1\132\3\3\21\0\3\3"+
    "\10\0\2\3\1\133\23\3\21\0\3\3\10\0\12\3"+
    "\1\134\13\3\21\0\3\3\10\0\5\3\1\135\20\3"+
    "\21\0\3\3\10\0\16\3\1\136\7\3\30\0\1\137"+
    "\52\0\3\3\10\0\4\3\1\140\21\3\21\0\3\3"+
    "\10\0\6\3\1\141\17\3\21\0\3\3\10\0\12\3"+
    "\1\142\13\3\21\0\3\3\10\0\2\3\1\143\23\3"+
    "\21\0\3\3\10\0\2\3\1\144\23\3\21\0\3\3"+
    "\10\0\6\3\1\145\17\3\21\0\3\3\10\0\4\3"+
    "\1\146\21\3\21\0\3\3\10\0\12\3\1\147\13\3"+
    "\21\0\3\3\10\0\22\3\1\150\3\3\21\0\3\3"+
    "\10\0\4\3\1\151\21\3\21\0\3\3\10\0\12\3"+
    "\1\152\13\3\21\0\3\3\10\0\10\3\1\153\15\3"+
    "\21\0\3\3\10\0\21\3\1\154\4\3\21\0\3\3"+
    "\10\0\2\3\1\155\23\3\21\0\3\3\10\0\5\3"+
    "\1\156\20\3\21\0\3\3\10\0\13\3\1\157\12\3"+
    "\21\0\3\3\10\0\20\3\1\160\5\3\21\0\3\3"+
    "\10\0\3\3\1\161\14\3\1\162\5\3\30\0\1\163"+
    "\52\0\3\3\10\0\5\3\1\164\20\3\21\0\3\3"+
    "\10\0\17\3\1\165\6\3\21\0\3\3\10\0\2\3"+
    "\1\166\23\3\21\0\3\3\10\0\3\3\1\167\22\3"+
    "\21\0\3\3\10\0\11\3\1\170\14\3\21\0\3\3"+
    "\10\0\3\3\1\171\22\3\21\0\3\3\10\0\10\3"+
    "\1\172\15\3\21\0\3\3\10\0\5\3\1\173\20\3"+
    "\21\0\3\3\10\0\2\3\1\174\23\3\21\0\3\3"+
    "\10\0\4\3\1\175\21\3\21\0\3\3\10\0\2\3"+
    "\1\176\23\3\21\0\3\3\10\0\21\3\1\177\4\3"+
    "\21\0\3\3\10\0\10\3\1\200\15\3\21\0\3\3"+
    "\10\0\2\3\1\201\23\3\30\0\1\137\1\0\1\202"+
    "\50\0\3\3\10\0\6\3\1\203\17\3\21\0\3\3"+
    "\10\0\2\3\1\204\23\3\21\0\3\3\10\0\5\3"+
    "\1\205\20\3\21\0\3\3\10\0\5\3\1\206\20\3"+
    "\21\0\3\3\10\0\3\3\1\207\22\3\21\0\3\3"+
    "\10\0\5\3\1\210\20\3\21\0\3\3\10\0\4\3"+
    "\1\211\21\3\21\0\3\3\10\0\6\3\1\212\17\3"+
    "\21\0\3\3\10\0\7\3\1\213\16\3\21\0\3\3"+
    "\10\0\5\3\1\214\20\3\21\0\3\3\10\0\10\3"+
    "\1\215\15\3\21\0\3\3\10\0\22\3\1\216\3\3"+
    "\21\0\3\3\10\0\16\3\1\217\7\3\21\0\3\3"+
    "\10\0\25\3\1\220\21\0\3\3\10\0\22\3\1\221"+
    "\3\3\21\0\3\3\10\0\2\3\1\222\23\3\21\0"+
    "\3\3\10\0\5\3\1\223\20\3\21\0\3\3\10\0"+
    "\10\3\1\224\15\3\21\0\3\3\10\0\2\3\1\225"+
    "\23\3\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4950];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\4\1\2\11\20\1\17\11\2\1\2\0"+
    "\3\11\30\1\2\11\1\0\25\1\1\0\23\1\1\0"+
    "\16\1\1\11\23\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

/**
 * Return a new Symbol with the given token id, and with the current line and
 * column numbers.
 */
Symbol newSym(int tokenId) {
    return new Symbol(tokenId, yyline, yycolumn);
}

/**
 * Return a new Symbol with the given token id, the current line and column
 * numbers, and the given token value.  The value is used for tokens such as
 * identifiers and numbers.
 */
Symbol newSym(int tokenId, Object value) {
    return new Symbol(tokenId, yyline, yycolumn, value);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  PascalLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return newSym(sym.INT, new Integer(yytext()));
            }
          case 58: break;
          case 2: 
            { System.out.println("Illegal char, '" + yytext() +
"' line: " + yyline + ", column: " + yychar);
            }
          case 59: break;
          case 3: 
            { return newSym(sym.IDENT, yytext());
            }
          case 60: break;
          case 4: 
            { return newSym(sym.DOT);
            }
          case 61: break;
          case 5: 
            { /* Ignore whitespace. */
            }
          case 62: break;
          case 6: 
            { return newSym(sym.MINUS);
            }
          case 63: break;
          case 7: 
            { return newSym(sym.GTR);
            }
          case 64: break;
          case 8: 
            { return newSym(sym.LESS);
            }
          case 65: break;
          case 9: 
            { return newSym(sym.TIMES);
            }
          case 66: break;
          case 10: 
            { return newSym(sym.PLUS);
            }
          case 67: break;
          case 11: 
            { return newSym(sym.DIVIDE);
            }
          case 68: break;
          case 12: 
            { return newSym(sym.BAND);
            }
          case 69: break;
          case 13: 
            { return newSym(sym.BOR);
            }
          case 70: break;
          case 14: 
            { return newSym(sym.LNOT);
            }
          case 71: break;
          case 15: 
            { return newSym(sym.MOD);
            }
          case 72: break;
          case 16: 
            { return newSym(sym.XOR);
            }
          case 73: break;
          case 17: 
            { return newSym(sym.SEMI);
            }
          case 74: break;
          case 18: 
            { return newSym(sym.COMMA);
            }
          case 75: break;
          case 19: 
            { return newSym(sym.LEFT_PAREN);
            }
          case 76: break;
          case 20: 
            { return newSym(sym.RT_PAREN);
            }
          case 77: break;
          case 21: 
            { return newSym(sym.LEFT_BRKT);
            }
          case 78: break;
          case 22: 
            { return newSym(sym.RT_BRKT);
            }
          case 79: break;
          case 23: 
            { return newSym(sym.EQ);
            }
          case 80: break;
          case 24: 
            { return newSym(sym.COLON);
            }
          case 81: break;
          case 25: 
            { return newSym(sym.REAL, new Double(yytext()));
            }
          case 82: break;
          case 26: 
            { return newSym(sym.NOT_EQ);
            }
          case 83: break;
          case 27: 
            { return newSym(sym.LESS_EQ);
            }
          case 84: break;
          case 28: 
            { return newSym(sym.GTR_EQ);
            }
          case 85: break;
          case 29: 
            { return newSym(sym.IF);
            }
          case 86: break;
          case 30: 
            { return newSym(sym.DO);
            }
          case 87: break;
          case 31: 
            { return newSym(sym.OR);
            }
          case 88: break;
          case 32: 
            { return newSym(sym.OF);
            }
          case 89: break;
          case 33: 
            { return newSym(sym.ASSMNT);
            }
          case 90: break;
          case 34: 
            { return newSym(sym.CHAR, new Character(yytext().charAt(1)));
            }
          case 91: break;
          case 35: 
            { return newSym(sym.VAR);
            }
          case 92: break;
          case 36: 
            { return newSym(sym.END);
            }
          case 93: break;
          case 37: 
            { return newSym(sym.AND);
            }
          case 94: break;
          case 38: 
            { return newSym(sym.ELSE);
            }
          case 95: break;
          case 39: 
            { return newSym(sym.REAL);
            }
          case 96: break;
          case 40: 
            { return newSym(sym.CHAR);
            }
          case 97: break;
          case 41: 
            { return newSym(sym.TRUE);
            }
          case 98: break;
          case 42: 
            { return newSym(sym.THEN);
            }
          case 99: break;
          case 43: 
            { return newSym(sym.BEGIN);
            }
          case 100: break;
          case 44: 
            { return newSym(sym.BREAK);
            }
          case 101: break;
          case 45: 
            { return newSym(sym.ARRAY);
            }
          case 102: break;
          case 46: 
            { return newSym(sym.WHILE);
            }
          case 103: break;
          case 47: 
            { return newSym(sym.FALSE);
            }
          case 104: break;
          case 48: 
            { /* For this stand-alone lexer, print out comments. */
                  System.out.println("Recognized comment: " + yytext());
            }
          case 105: break;
          case 49: 
            { return newSym(sym.ASSIGN);
            }
          case 106: break;
          case 50: 
            { return newSym(sym.RETURN);
            }
          case 107: break;
          case 51: 
            { return newSym(sym.STRING);
            }
          case 108: break;
          case 52: 
            { return newSym(sym.BOOLEAN);
            }
          case 109: break;
          case 53: 
            { return newSym(sym.INTEGER);
            }
          case 110: break;
          case 54: 
            { return newSym(sym.PROGRAM);
            }
          case 111: break;
          case 55: 
            { return newSym(sym.CONTINUE);
            }
          case 112: break;
          case 56: 
            { return newSym(sym.FUNCTION);
            }
          case 113: break;
          case 57: 
            { return newSym(sym.PROCEDURE);
            }
          case 114: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
